version: '2'
services:
  wiki:
    #build: ./../../../ # Uncomment to build
    image: kristophjunge/mediawiki
    environment:
      MEDIAWIKI_SERVER: https://localhost
      MEDIAWIKI_SITENAME: MyWiki
      MEDIAWIKI_LANGUAGE_CODE: en
      MEDIAWIKI_SECRET_KEY: mysecret
      MEDIAWIKI_DB_TYPE: sqlite
      MEDIAWIKI_DB_NAME: wikidb
      MEDIAWIKI_ENABLE_UPLOADS: 1
      MEDIAWIKI_ENABLE_VISUAL_EDITOR: 0
      MEDIAWIKI_DEFAULT_SKIN: vector
    ports:
    - "8080:80"
    volumes:
    - /srv/mediawiki/images:/var/www/mediawiki/images
    - /srv/mediawiki/data:/data
    #- ./../../../testdata/logo.png:/var/www/mediawiki/resources/assets/wiki.png:ro
    #- ./../../../testdata/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro
